# config/packages/symfonycasts_reset_password.yaml

symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    throttle_limit: 5 # Limite le nombre de demandes dans une période donnée
    lifetime: 3600 # Durée de validité des tokens (3600 secondes = 1 heure)
    enable_garbage_collection: true # Optionnel : activez la collecte des requêtes expirées
