security:
    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                # Uncomment the line below to specify a target after logout
                # target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                # Uncomment to always enable "remember me" without requiring a checkbox
                # always_remember_me: true

    # Access Control
    access_control:
    # Define access restrictions here
    # Example:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

# Test-specific configuration
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4      # Lowest possible value for bcrypt
                time_cost: 3  # Lowest possible value for Argon2id
                memory_cost: 10 # Lowest possible value for Argon2id
